### PR TITLE
Update hello.test.ts

### PR DESCRIPTION
**Pull request by mmun**

### CODE REVIEW

**Comment by notriddle** [comment]
> edited by mmun

Are you trying to patch bors to give a smaller notification about completed builds?

**Comment by mmun** [comment]
@notriddle I was just showing one of my coworkers and they mentioned it was large. I jokingly edited it saying it's not a big deal and we can tweak it if we want. I wouldn't read too much into it :)

**Comment by notriddle** [comment]
Makes sense. File an issue?

**Pull request merged**
